# Generated by Django 4.1.1 on 2022-09-17 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=25, verbose_name='Имя автора ')),
                ('comment_text', models.TextField(blank=True, verbose_name='Текст комментария ')),
                ('women_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.women')),
            ],
        ),
    ]
